server:
  port: 8191
  servlet:
    context-path: /store
integrations:
  storage: /storage
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
APP_RESOURCES_PATH: /app/resources
APP_STORAGE_PATH: app/storage